### ISSUE TITLE
Summary command

### ISSUE THREAD

**Issue by ziima** [adamalton/django-csp-reports#21]
Add a command to print summary about the CSP reports.

### Usage ###
```
make_csp_summary [--since date] [--to date] [--top number]
```
by default prints the summary of yesterday's reports. `--since` and `--to` modify the interval. `--top` defines the size of each limit section, 10 by default.

### Content ###
 * Total number of reports, number of invalid reports.
 * Top sources (`document_uri`) + examples (source, blocked URI)
 * Top violated directives + examples (source, blocked URI)
 * Top blocked URIs + examples (source, blocked URI)
 * Examples of invalid reports

URIs will be merged regardless of `query` and `fragment`.

### Think about ###
 * Summary customization

**Comment by ziima** [comment]
Request for comments. I hope I'll start implementing this week.

**Comment by adamalton** [comment]
Seems like a good idea.  A few thoughts:

* I'm guessing that the most useful info will be the `document_uri` plus the source and blocked URI.  The question with the `document_uri` is whether to strip off the query string before grouping them.  Otherwise, something like a tracking ID in the query string could mean that errors from the same page don't get grouped.  So I'm thinking that yes we should, but then in the example(s) we should show the full URL including query string, just in case it's something in the query string that's causing the problem.
* In terms of fetching and grouping the data, it would be good to do that separately from the management command, just so that if someone wants to feed the data into a CSV file or create an API for accessing it, the data fetching functions are reusable, with only the formatting for the terminal happening in the command itself.

Thanks!
Adam

**Comment by ziima** [comment]
* Switched the order of blocks in the description.
 * Yes, I intent split the summary collector into a module so it can be used for other outputs.
