### ISSUE TITLE
Make CSP Model Customable

### ISSUE THREAD

**Issue by anderermark** [adamalton/django-csp-reports#56]
Hey,

thanks for the project so far! :)

I could like to add an acknowledge function to the reports (instead of deleting them). Therefore I would have to add a field to the csp model (or create a construct with an extra table pointing at acknowledged reports, which would be kinda clumsy to use in django admin).

My use case is probably only one example of how one would adjust the model to it's individual needs.

I would offer to create a PR to enable customization of the used model doing the following steps:

- I would propose to add a setting for specifying the used csp model and transform the current model into an abstract base class with default implementation. That's a pattern you often find in django's third party packages.

- Before doing that, I could refactor the settings access and gather app settings in one central module, if that's appreciated.

Please tell me, what you think about it :)

**Comment by adamalton** [comment]
Hey, thanks for the ticket. I like your idea of making the model configurable - your use case makes sense and I agree that people may have other use cases for the same feature. I'd gratefully accept a pull request to implement this.

I'm not so clear what you mean about refactoring the settings. Can you give a bit more detail on what you mean there?

Thanks!

**Comment by adamalton** [comment]
Ah ok, yes, makes sense.

I agree it would be nice to move the settings out of their current location in `utils.py` and put them into a dedicated `settings.py` or `conf.py` module.

The approach you suggest with the `Settings` class and `@property` methods looks nice. Just note that in the current implementation there is some deliberate "caching" going on so that we don't have to re-import the additional handlers or filter function every time they are accessed. Maybe the benefit of having them more easily overrideable outweighs the downside of the overhead of re-importing them every time they're accessed, I'm not sure.

I guess that an _optimal_ way of doing it would be to cache those values and then use Django's `setting_changed` signal to un-cache them if they're changed. But if you don't want to go to that effort them I trust you to just make a decision about which way you think is best.

**Comment by maqnius** [comment]
This is me (@anderermark)  but now with my personal account, which is more convenient to use for me. I'll stick to this account now. Sorry for the confusion.

I implemented the changes to the settings module in pull request #57. I think it might be easier to argue based on that. As far as I can see, no caching behavior has changed. Maybe you could have a look at the pr and leave your thoughts there :)

In fact, the `conf.Settings` class does pretty much the same job as the `utils.Config` class - a little more explicit though and for all app related settings.

**Comment by adamalton** [comment]
Yep! It's released! https://pypi.org/project/django-csp-reports/1.9.0/

Thank you for all your work on this. Really appreciated.
